#include <stdio.h>
#include <ctime>
#include <cstring>
#include <sstream>
#include <iomanip>
#include <iostream>
#include <cstdlib> // Required for rand() and srand()
#include <mpi.h>

/**
 * @brief Estimates Pi using the Monte Carlo method (dart-throwing) in parallel.
 * * Each process calculates hits for a portion of 'n' total points, and MPI_Reduce
 * aggregates the results on rank 0 to compute the final estimate.
 * * @param n The total number of points (darts) to throw across all processes.
 * @return The estimated value of Pi on rank 0, and 0.0 on all other ranks.
 */
double pi_calc(long int n) {
    // Get rank and size
    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    // 1. Calculate local work (integer division is sufficient for large n)
    long int local_n = n / size;
    long long local_hits = 0; // Use long long to safely accumulate large counts

    // 2. Seed the random number generator uniquely for each process.
    // This is crucial for Monte Carlo simulations to ensure independent,
    // uncorrelated random sequences across processes.
    srand(time(NULL) + rank); 

    // 3. Local Simulation (Dart throwing)
    for (long int i = 0; i < local_n; ++i) {
        // Generate random coordinates x and y in the range [0.0, 1.0].
        // The coordinates are generated by dividing the random integer by the maximum
        // possible random integer (RAND_MAX) to normalize it.
        double x = (double)rand() / RAND_MAX;
        double y = (double)rand() / RAND_MAX;

        // Check if the point (x, y) is inside the unit quarter circle.
        // The distance from the origin (0,0) is sqrt(x^2 + y^2).
        // If distance <= 1, the point is inside. We check distance^2 <= 1^2 to avoid sqrt.
        if (x * x + y * y <= 1.0) {
            local_hits++;
        }
    }

    // 4. Aggregate Results
    long long total_hits = 0;
    // MPI_Reduce sums up all 'local_hits' from every process and stores the
    // result in 'total_hits' on the root process (rank 0).
    // Use MPI_LONG_LONG for the datatype.
    MPI_Reduce(&local_hits, &total_hits, 1, MPI_LONG_LONG, MPI_SUM, 0, MPI_COMM_WORLD);

    // 5. Calculate Pi (only on Rank 0)
    if (rank == 0) {
        // Pi is estimated by 4 * (Points in Circle / Total Points)
        // Area_circle / Area_square = (Pi*r^2 / 4) / r^2 = Pi / 4
        // Pi = 4 * (total_hits / n)
        return 4.0 * ((double)total_hits / n);
    }

    // Non-root processes return 0.0, as their result is only the reduction result.
    return 0.0;
}